import {
  MonitorSmartphone,
  Cpu,
  Gamepad2,
  Smartphone,
  Globe2,
  Code,
  Rocket,
  GraduationCap,
  HeartPulse,
  DollarSign,
  Megaphone,
  Users,
  Palette,
  Music,
  Film,
  Book,
  Tv,
  Dumbbell,
  Plane,
  Check,
  Utensils,
  Leaf,
  ShoppingCart,
} from 'lucide-react';

export const categories = [
  { persian: "تکنولوژی", english: "technology", icon: MonitorSmartphone },
  { persian: "نرم‌افزار", english: "software", icon: Cpu },
  { persian: "بازی", english: "game", icon: Gamepad2 },
  { persian: "اپلیکیشن", english: "app", icon: Smartphone },
  { persian: "وب‌سایت", english: "website", icon: Globe2 },
  { persian: "برنامه نویسی" , english: "developer", icon: Code },
  { persian: "استارتاپ", english: "startup", icon: Rocket },
  { persian: "آموزش", english: "education", icon: GraduationCap },
  { persian: "سلامت", english: "health", icon: HeartPulse },
  { persian: "مالی", english: "finance", icon: DollarSign },
  { persian: "بازاریابی", english: "marketing", icon: Megaphone },
  { persian: "اجتماعی" , english: "social", icon: Users },
  { persian: "هنر و طراحی", english: "design", icon: Palette },
  { persian: "موسیقی", english: "music", icon: Music },
  { persian: "فیلم و ویدئو", english: "film", icon: Film },
  { persian: "کتاب", english: "book", icon: Book },
  { persian: "سرگرمی", english: "entertainment", icon: Tv },
  { persian: "ورزش", english: "sports", icon: Dumbbell },
  { persian: "مسافرت", english: "travel", icon: Plane },
  { persian: "سبک زندگی", english: "lifestyle", icon: Check},
  { persian: "غذا و نوشیدنی", english: "food", icon: Utensils },
  { persian: "محیط زیست", english: "environment", icon: Leaf },
  { persian: "تجارت", english: "e-commerce", icon: ShoppingCart },
];
